### ISSUE TITLE
ImportError: cannot import name 'smiles2graph' from 'ogb.utils' 

### ISSUE THREAD

**Issue by mostafaelhoushi** [XiaoxinHe/Graph-ViT-MLPMixer#2]
Thanks for open sourcing the code.
I am following the README and getting this error:
```
$ python -m train.exp
Traceback (most recent call last):
  File "/data/home/melhoushi/miniconda/envs/graph_mlpmixer/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/data/home/melhoushi/miniconda/envs/graph_mlpmixer/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/data/home/melhoushi/Graph-MLPMixer/train/exp.py", line 4, in <module>
    from core.get_data import create_dataset
  File "/data/home/melhoushi/Graph-MLPMixer/core/get_data.py", line 7, in <module>
    from core.data_utils.peptides_functional import PeptidesFunctionalDataset
  File "/data/home/melhoushi/Graph-MLPMixer/core/data_utils/peptides_functional.py", line 8, in <module>
    from ogb.utils import smiles2graph
ImportError: cannot import name 'smiles2graph' from 'ogb.utils' (/data/home/melhoushi/miniconda/envs/graph_mlpmixer/lib/python3.8/site-packages/ogb/utils/__init__.py)
```

**Comment by XiaoxinHe** [comment]
Hi, 

Have you run the following command?
```
# LRGB
conda install openbabel fsspec rdkit -c conda-forge
```

**Comment by mostafaelhoushi** [comment]
I did run this command... but when running one of the training commands, I got an error with pandas... so I changed the pandas version, then hit this `smiles2graph` error...

I am re-running all the setup commands from scrach and see how it goes

**Comment by mostafaelhoushi** [comment]
OK. I went back and re-ran all the README Getting Started commands, and now I am hitting this:
```
$  python -m train.cifar10
Traceback (most recent call last):
  File "/data/home/melhoushi/miniconda/envs/graph_mlpmixer/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/data/home/melhoushi/miniconda/envs/graph_mlpmixer/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/data/home/melhoushi/Graph-MLPMixer/train/cifar10.py", line 4, in <module>
    from core.get_data import create_dataset
  File "/data/home/melhoushi/Graph-MLPMixer/core/get_data.py", line 7, in <module>
    from core.data_utils.peptides_functional import PeptidesFunctionalDataset
  File "/data/home/melhoushi/Graph-MLPMixer/core/data_utils/peptides_functional.py", line 6, in <module>
    import pandas as pd
  File "/data/home/melhoushi/miniconda/envs/graph_mlpmixer/lib/python3.8/site-packages/pandas/__init__.py", line 48, in <module>
    from pandas.core.api import (
  File "/data/home/melhoushi/miniconda/envs/graph_mlpmixer/lib/python3.8/site-packages/pandas/core/api.py", line 48, in <module>
    from pandas.core.groupby import (
  File "/data/home/melhoushi/miniconda/envs/graph_mlpmixer/lib/python3.8/site-packages/pandas/core/groupby/__init__.py", line 1, in <module>
    from pandas.core.groupby.generic import (
  File "/data/home/melhoushi/miniconda/envs/graph_mlpmixer/lib/python3.8/site-packages/pandas/core/groupby/generic.py", line 70, in <module>
    from pandas.core.frame import DataFrame
  File "/data/home/melhoushi/miniconda/envs/graph_mlpmixer/lib/python3.8/site-packages/pandas/core/frame.py", line 157, in <module>
    from pandas.core.generic import NDFrame
  File "/data/home/melhoushi/miniconda/envs/graph_mlpmixer/lib/python3.8/site-packages/pandas/core/generic.py", line 152, in <module>
    from pandas.core.window import (
  File "/data/home/melhoushi/miniconda/envs/graph_mlpmixer/lib/python3.8/site-packages/pandas/core/window/__init__.py", line 1, in <module>
    from pandas.core.window.ewm import (  # noqa:F401
  File "/data/home/melhoushi/miniconda/envs/graph_mlpmixer/lib/python3.8/site-packages/pandas/core/window/ewm.py", line 12, in <module>
    import pandas._libs.window.aggregations as window_aggregations
ImportError: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by /data/home/melhoushi/miniconda/envs/graph_mlpmixer/lib/python3.8/site-packages/pandas/_libs/window/aggregations.cpython-38-x86_64-linux-gnu.so)
srun: error: learnfair-st-p4d24xlarge-12: task 0: Exited with exit code 1
```

I was able to solve this `GLIBC` error by downgrading the pandas version, but that lead me to hit the `ImportError: cannot import name 'smiles2graph' from 'ogb.utils'` error.

Maybe you can share the version of each of those libraries that are working with you?

**Comment by XiaoxinHe** [comment]
Hi,  the packages I am working with:

`conda env export -n graph_mlpmixer > ENV.yml`

```
name: graph_mlpmixer
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_kmp_llvm
  - blas=2.116=openblas
  - blas-devel=3.9.0=16_linux64_openblas
  - boost=1.74.0=py38h2b96118_5
  - boost-cpp=1.74.0=h75c5d50_8
  - bottleneck=1.3.5=py38h26c90d9_1
  - bzip2=1.0.8=h7f98852_4
  - ca-certificates=2022.12.7=ha878542_0
  - cairo=1.16.0=hb05425b_3
  - certifi=2022.12.7=pyhd8ed1ab_0
  - cycler=0.11.0=pyhd8ed1ab_0
  - expat=2.4.9=h6a678d5_0
  - fontconfig=2.14.1=hc2a2eb6_0
  - freetype=2.12.1=hca18f0e_1
  - fsspec=2022.11.0=pyhd8ed1ab_0
  - glib=2.69.1=he621ea3_2
  - icu=70.1=h27087fc_0
  - jbig=2.1=h7f98852_2003
  - jpeg=9e=h166bdaf_2
  - kiwisolver=1.4.4=py38h6a678d5_0
  - ld_impl_linux-64=2.38=h1181459_1
  - lerc=3.0=h295c915_0
  - libblas=3.9.0=16_linux64_openblas
  - libcblas=3.9.0=16_linux64_openblas
  - libdeflate=1.8=h7f8727e_5
  - libffi=3.4.2=h6a678d5_6
  - libgcc-ng=12.2.0=h65d4601_19
  - libgfortran-ng=12.2.0=h69a702a_19
  - libgfortran5=12.2.0=h337968e_19
  - libiconv=1.17=h166bdaf_0
  - liblapack=3.9.0=16_linux64_openblas
  - liblapacke=3.9.0=16_linux64_openblas
  - libopenblas=0.3.21=pthreads_h78a6416_3
  - libpng=1.6.39=h753d276_0
  - libstdcxx-ng=11.2.0=h1234567_1
  - libtiff=4.3.0=h6f004c6_2
  - libuuid=2.32.1=h7f98852_1000
  - libwebp-base=1.2.4=h166bdaf_0
  - libxcb=1.15=h7f8727e_0
  - libxml2=2.10.3=h7463322_0
  - libzlib=1.2.13=h166bdaf_4
  - llvm-openmp=15.0.6=he0ac6c6_0
  - lz4-c=1.9.3=h9c3ff4c_1
  - matplotlib-base=3.4.3=py38hf4fb855_1
  - ncurses=6.3=h5eee18b_3
  - numexpr=2.8.4=py38hd2a5715_0
  - olefile=0.46=pyh9f0ad1d_1
  - openbabel=3.1.1=py38hd2c4bc0_3
  - openblas=0.3.21=pthreads_h320a7e8_3
  - openssl=1.1.1s=h0b41bf4_1
  - packaging=22.0=pyhd8ed1ab_0
  - pcre=8.45=h9c3ff4c_0
  - pip=22.3.1=py38h06a4308_0
  - pixman=0.40.0=h36c2ea0_0
  - pycairo=1.23.0=py38h190342e_0
  - pyparsing=3.0.9=pyhd8ed1ab_0
  - python=3.8.15=h7a1cb2a_2
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python_abi=3.8=2_cp38
  - pytz=2022.7=pyhd8ed1ab_0
  - rdkit=2022.03.2=py38ha829ea6_0
  - readline=8.2=h5eee18b_0
  - reportlab=3.5.67=py38hfdd840d_1
  - setuptools=65.5.0=py38h06a4308_0
  - six=1.16.0=pyh6c4a22f_0
  - sqlalchemy=1.3.24=py38h0a891b7_1
  - sqlite=3.40.0=h5082296_0
  - tk=8.6.12=h1ccaba5_0
  - tornado=6.2=py38h0a891b7_1
  - wheel=0.37.1=pyhd3eb1b0_0
  - xz=5.2.8=h5eee18b_0
  - zlib=1.2.13=h166bdaf_4
  - zstd=1.5.2=h8a70e8d_1
 - pip:
      - absl-py==1.3.0
      - cachetools==5.2.0
      - charset-normalizer==2.1.1
      - einops==0.6.0
      - google-auth==2.15.0
      - google-auth-oauthlib==0.4.6
      - grpcio==1.51.1
      - idna==3.4
      - importlib-metadata==5.2.0
      - jinja2==3.1.2
      - joblib==1.2.0
      - littleutils==0.2.2
      - markdown==3.4.1
      - markupsafe==2.1.1
      - metis==0.2a5
      - networkx==2.8.8
      - numpy==1.24.1
      - oauthlib==3.2.2
      - ogb==1.3.5
      - outdated==0.2.2
      - pandas==1.0.1
      - pillow==9.3.0
      - protobuf==3.20.3
      - psutil==5.9.4
      - pyasn1==0.4.8
      - pyasn1-modules==0.2.8
      - pyyaml==6.0
      - requests==2.28.1
      - requests-oauthlib==1.3.1
      - rsa==4.9
      - scikit-learn==1.2.0
      - scipy==1.9.3
      - tensorboard==2.11.0
      - tensorboard-data-server==0.6.1
      - tensorboard-plugin-wit==1.8.1
      - threadpoolctl==3.1.0
      - torch==1.11.0+cu113
      - torch-cluster==1.6.0
      - torch-geometric==2.2.0
      - torch-scatter==2.1.0
      - torch-sparse==0.6.16
      - torchaudio==0.11.0+cu113
      - torchvision==0.12.0+cu113
      - tqdm==4.64.1
      - typing-extensions==4.4.0
      - urllib3==1.26.13
      - werkzeug==2.2.2
      - yacs==0.1.8
      - zipp==3.11.0
prefix: /home/xiaoxin/miniconda3/envs/graph_mlpmixer
```

**Comment by mostafaelhoushi** [comment]
Thanks @XiaoxinHe !
I did some further debugging.

## Cause
`Graph-MLPMixer/core/data_utils/peptides_functional.py` imports:
```
from ogb.utils import smiles2graph
```

Looking at [`ogb/utils`](https://github.com/snap-stanford/ogb/blob/553dc0b70a7a3f95bb47b8e09a1e06ae0aff1e4f/ogb/utils/__init__.py#L1-L4) we find this:
```
try:
    from .mol import smiles2graph
except ImportError:
    pass
``` 

removing the `try... except` block, we find that `from .mol import smiles2graph` threw this error:
```
ImportError: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.29' not found
```

## Solution
After searching online, it seems that `GLIBCXX_3.4.29'  exists in Miniconda library but not in the Linux system libraries. Hence, these commands seem to solve the problem:
```
LD_LIBRARY_PATH=$LD_LIBRARY_PATH:~/miniconda/lib/
ln -s ~/miniconda/lib/libstdc++.so.6.0.29 ~/miniconda/lib/libstdc++.so.6
```

**Comment by XiaoxinHe** [comment]
Thanks for identifying the cause and providing the solution!
