### ISSUE TITLE
UnboundLocalError: local variable 'config_string' referenced before assignment

### ISSUE THREAD

**Issue by DreeeamBoard** [XiaoxinHe/Graph-ViT-MLPMixer#7]
Thank you for open sourcing the code.
I'm getting this error :

(graph_mlpmixer) dskim@kaist:~/Graph-ViT-MLPMixer$ python -m train.exp
Traceback (most recent call last):
  File "/data/home/dskim/.conda/envs/graph_mlpmixer/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/data/home/dskim/.conda/envs/graph_mlpmixer/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/data/home/dskim/Graph-ViT-MLPMixer/train/exp.py", line 62, in <module>
    run_k_fold(cfg, create_dataset, create_model, train, test, k=5)
  File "/data/home/dskim/Graph-ViT-MLPMixer/core/train_helper.py", line 178, in run_k_fold
    writer, logger = config_logger(cfg)
  File "/data/home/dskim/Graph-ViT-MLPMixer/core/log.py", line 29, in config_logger
    writer_folder = os.path.join(OUT_PATH, data_name, config_string)
UnboundLocalError: local variable 'config_string' referenced before assignment

**Comment by XiaoxinHe** [comment]
Hi,

Thank you for bringing this to my attention. I have addressed [this issue](https://github.com/XiaoxinHe/Graph-ViT-MLPMixer/commit/0d66dd1b0d8376e9252a73d60c10940ac626ca81). Please rerun the code to verify the fix."
